import React from "react";
import "./styles/Alphabet.css";

const Alphabet = () => (
  <div className="table-div">
    <table className="table">
      <tbody>
        <tr>
          <th>Name</th>
          <th>Upper Case</th>
          <th>Lower Case</th>
        </tr>
        <tr>
          <td>Alpha</td>
          <td>Α</td>
          <td>α</td>
        </tr>
        <tr>
          <td>Beta</td>
          <td>Β</td>
          <td>β</td>
        </tr>
        <tr>
          <td>Gamma</td>
          <td>Γ</td>
          <td>γ</td>
        </tr>
        <tr>
          <td>Delta</td>
          <td>Δ</td>
          <td>δ</td>
        </tr>
        <tr>
          <td>Epsilon</td>
          <td>Ε</td>
          <td>ε</td>
        </tr>
        <tr>
          <td>Zeta</td>
          <td>Ζ</td>
          <td>ζ</td>
        </tr>
        <tr>
          <td>Eta</td>
          <td>H</td>
          <td>η</td>
        </tr>
        <tr>
          <td>Theta</td>
          <td>Θ</td>
          <td>θ</td>
        </tr>
        <tr>
          <td>Iota</td>
          <td>Ι</td>
          <td>ι</td>
        </tr>
        <tr>
          <td>Kappa</td>
          <td>Κ</td>
          <td>κ</td>
        </tr>
        <tr>
          <td>Lambda</td>
          <td>Λ</td>
          <td>λ</td>
        </tr>
        <tr>
          <td>Mu</td>
          <td>Μ</td>
          <td>μ</td>
        </tr>
        <tr>
          <td>Nu</td>
          <td>Ν</td>
          <td>ν</td>
        </tr>
        <tr>
          <td>Xi</td>
          <td>Ξ</td>
          <td>ξ</td>
        </tr>
        <tr>
          <td>Omicron</td>
          <td>Ο</td>
          <td>ο</td>
        </tr>
        <tr>
          <td>Pi</td>
          <td>Π</td>
          <td>π</td>
        </tr>
        <tr>
          <td>Rho</td>
          <td>Ρ</td>
          <td>ρ</td>
        </tr>
        <tr>
          <td>Sigma</td>
          <td>Σ</td>
          <td>σ/ς</td>
        </tr>
        <tr>
          <td>Tau</td>
          <td>Τ</td>
          <td>τ</td>
        </tr>
        <tr>
          <td>Upsilon</td>
          <td>Υ</td>
          <td>υ</td>
        </tr>
        <tr>
          <td>Phi</td>
          <td>Φ</td>
          <td>φ</td>
        </tr>
        <tr>
          <td>Chi</td>
          <td>Χ</td>
          <td>χ</td>
        </tr>
        <tr>
          <td>Psi</td>
          <td>Ψ</td>
          <td>ψ</td>
        </tr>
        <tr>
          <td>Omega</td>
          <td>Ω</td>
          <td>ω</td>
        </tr>
      </tbody>
    </table>
  </div>
);

export default Alphabet;
